version: '3.7'

services:
  ipc_database:
    image: postgres:14.5-alpine
    container_name: ipc_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123

  

  ipc_app: &app
    image: ipc-server
    build: .
    container_name: ipc_app
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    depends_on:
      - ipc_database
    command:
      - bash
      - -c
      - |
        flask db upgrade -d ais_server/migrations
        gunicorn wsgi:application

